### PR TITLE
Rewrite TrailingSpacesFixer

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
Please remember to cherry pick this commits into your branch instead of merging them

**Comment by SpacePossum** [comment]
@keradus great! thanks so much! : D

You are better of making a PR of yourself and just add my test, because I'll mess this up. Most likely by adding this, renaming things and all the typical stuff I do and then rebase, squash and merge this thing sback and forward and I loose your contribution or more likely somehow mark it as like I did it. Not on purpose, but this always happends when I try to be smart on github ;)

**Comment by keradus** [comment]
It would be cool if you learn how to do it right ;) And I can help with that.

```bash
git checkout TrailingSpacesFixer_fix # to be on the right branch
git commit --amend -m "new_message" # only if you want to change message of your commit
git fetch upstream # fetch original branches from FriendsOfPhp
git rebase upstream/1.8 # to be on top of original 1.8 branch
git fetch keradus # fetch my changes
git cherry-pick 380563a556e2623ba69b4f31af121aaa11c85262 7fbcaead17ed00a89d68c3fcfda2d1891eb48ab6 # apply both commits from this PR
```

That could do the trick. No need to squash anything here. Please ask if you have any questions ;)

**Comment by tiemevanveen** [comment]
Tnx! Not just for SpacePossum :D! A bit off topic, but a merge after the rebase (instead of cherry picking) would only be less ideal because it will create a merge commit, which is not that nice in a PR history right?

**Comment by SpacePossum** [comment]
Seems to have worked :)
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1224
thanks @keradus @SamBurns-awin and @tiemevanveen!

**Comment by sstok** [comment]
You can actually merge, just don't use the GitHub web interface as that uses --no-ff creating a merge commit.

With Gush 1.16 (pending release) you can easily solve this with: `gush pull-request:merge --org=SpacePossum --fast-forward 2` which merges the pull-request using fast forward :+1:

**Comment by SpacePossum** [comment]
thanks for insight @sstok !   :+1:

**Pull request closed without merging**
